/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2mariorodriguez;

import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class Encuesta extends javax.swing.JFrame {

    /**
     * Creates new form Encuesta
     */
    public Encuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Rsi = new javax.swing.JRadioButton();
        Rno = new javax.swing.JRadioButton();
        Bregistrar = new javax.swing.JButton();
        Tnombre = new javax.swing.JTextField();
        Tedad = new javax.swing.JTextField();
        Tcorreo = new javax.swing.JTextField();
        Lnumero = new javax.swing.JLabel();
        Breporteencu = new javax.swing.JButton();
        Bcarroprop = new javax.swing.JButton();
        Bsincarro = new javax.swing.JButton();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("FORMULARIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 20, 150, 16);

        jLabel2.setText("NUMERO DE ENCUESTA:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 150, 16);

        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 110, 70, 16);

        jLabel4.setText("EDAD:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 150, 40, 16);

        jLabel5.setText("CORREO ELECTRONICO:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 190, 160, 16);

        jLabel6.setText("CARRO PROPIO:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 230, 100, 16);

        buttonGroup1.add(Rsi);
        Rsi.setText("SI");
        getContentPane().add(Rsi);
        Rsi.setBounds(140, 230, 40, 21);

        buttonGroup1.add(Rno);
        Rno.setText("NO");
        getContentPane().add(Rno);
        Rno.setBounds(190, 230, 50, 21);

        Bregistrar.setText("REGISTRAR");
        Bregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(Bregistrar);
        Bregistrar.setBounds(140, 290, 110, 23);

        Tnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnombreActionPerformed(evt);
            }
        });
        getContentPane().add(Tnombre);
        Tnombre.setBounds(100, 110, 410, 22);

        Tedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TedadActionPerformed(evt);
            }
        });
        getContentPane().add(Tedad);
        Tedad.setBounds(90, 150, 110, 22);
        getContentPane().add(Tcorreo);
        Tcorreo.setBounds(180, 190, 330, 22);
        getContentPane().add(Lnumero);
        Lnumero.setBounds(170, 70, 30, 20);

        Breporteencu.setText("REPORTE ENCUESTAS");
        Breporteencu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreporteencuActionPerformed(evt);
            }
        });
        getContentPane().add(Breporteencu);
        Breporteencu.setBounds(320, 270, 200, 23);

        Bcarroprop.setText("REPORTE CARRO PROPIO");
        Bcarroprop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcarropropActionPerformed(evt);
            }
        });
        getContentPane().add(Bcarroprop);
        Bcarroprop.setBounds(320, 300, 200, 23);

        Bsincarro.setText("REPORTE SIN CARRO");
        Bsincarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsincarroActionPerformed(evt);
            }
        });
        getContentPane().add(Bsincarro);
        Bsincarro.setBounds(320, 330, 200, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregistrarActionPerformed
      Formulario.setNombre(Tnombre.getText());
      Formulario.setEdad(Integer.parseInt(Tedad.getText()));
      Formulario.setCorreo(Tcorreo.getText());
      
      Tnombre.setText("");
      Tedad.setText("");
      Tcorreo.setText("");
      
      
        
        if ( Tnombre.equals("")) {
            JOptionPane.showMessageDialog(null, "CAMPO OBLIGATORIO");
        }
        if (Tedad.equals(" ")) {
            JOptionPane.showMessageDialog(null, "CAMPO OBLIGATORIO");
        }
        if (Tcorreo.equals(" ")) {
            JOptionPane.showMessageDialog(null, "CAMPO OBLIGATORIO");
        }
        
        Formulario.Codigo();
        
        Formulario.Edad();
    }//GEN-LAST:event_BregistrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//        Formulario.Codigo();
//        Lnumero.setText(String.valueOf(Formulario.Codigo()));
    }//GEN-LAST:event_formWindowActivated

    private void TnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnombreActionPerformed
       
    }//GEN-LAST:event_TnombreActionPerformed

    private void TedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TedadActionPerformed
        Formulario.Edad();
    }//GEN-LAST:event_TedadActionPerformed

    private void BreporteencuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreporteencuActionPerformed
        EncuestasRealizadas encuesta = new EncuestasRealizadas();
        encuesta.setBounds(480, 200, 400, 320);
        encuesta.setVisible(true);
        this.hide();
    }//GEN-LAST:event_BreporteencuActionPerformed

    private void BcarropropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcarropropActionPerformed
        CarroPropio ventana = new CarroPropio();
        ventana.setBounds(480, 200, 400, 320);
        ventana.setVisible(true);
        this.hide();
    }//GEN-LAST:event_BcarropropActionPerformed

    private void BsincarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsincarroActionPerformed
        SinCarro imagen = new SinCarro();
        imagen.setBounds(480, 200, 400, 320);
        imagen.setVisible(true);
        this.hide();
    }//GEN-LAST:event_BsincarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcarroprop;
    private javax.swing.JButton Bregistrar;
    private javax.swing.JButton Breporteencu;
    private javax.swing.JButton Bsincarro;
    private javax.swing.JLabel Lnumero;
    private javax.swing.JRadioButton Rno;
    private javax.swing.JRadioButton Rsi;
    private javax.swing.JTextField Tcorreo;
    private javax.swing.JTextField Tedad;
    private javax.swing.JTextField Tnombre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
